### ISSUE TITLE
background subtract analysis

### ISSUE THREAD

**Issue by mingness** [mingness/alternativesoundtrack#19]
shows video with background image subtracted.

**Comment by hamoid** [comment]
There's an interesting example here: https://github.com/atduskgreg/opencv-processing

(see the photo with the street crossing, cars and people)

**Comment by mingness** [comment]
This is not an analysis, but an image processing - the distinction is that an analysis feeds directly to OSC and sound making. This, instead, processes the video such that it can be operated by an analysis.
